# Generated by Django 5.1.1 on 2024-09-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='description',
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
